### ISSUE TITLE
Error when load Lora

### ISSUE THREAD

**Issue by YellowStar11** [Linaqruf/sd-notebook-collection#34]
Lora already installed but i can't use it. plz help me!

locon load lora method
loading Lora /content/cagliostro-colab-ui/models/Lora/koreanDollLikeness_v20.safetensors: AttributeError
Traceback (most recent call last):
  File "/content/cagliostro-colab-ui/extensions/a1111-sd-webui-locon/scripts/../../../extensions-builtin/Lora/lora.py", line 222, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/cagliostro-colab-ui/extensions/a1111-sd-webui-locon/scripts/main.py", line 370, in load_lora
    is_sd2 = 'model_transformer_resblocks' in shared.sd_model.lora_layer_mapping
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LatentDiffusion' object has no attribute 'lora_layer_mapping'

**Comment by Linaqruf** [comment]
what model name and what lora link?

**Comment by YellowStar11** [comment]
@Linaqruf 

https://huggingface.co/Kanbara/doll-likeness-series/resolve/main/koreanDollLikeness_v20.safetensors

**Comment by Linaqruf** [comment]
![image](https://github.com/Linaqruf/sd-notebook-collection/assets/50163983/7809a17c-0499-4766-9968-8d70c43da03d)
the lora is loaded successfully with chilloutmix-ni as a model
I think the problem is
- Your model isn't SDv1.x model because KoreanDollLikeness was based on that 
- The LoRA is corrupted after downloaded
- This probably happens in `repo_type` = AUTOMATIC1111, and AUTOMATIC1111-Dev

![image](https://github.com/Linaqruf/sd-notebook-collection/assets/50163983/f8262c74-ef29-4057-ae8b-91c5db0d8804)

**Comment by Linaqruf** [comment]
Hi, now I understand the problem. The problem is as follows:
- Your LoRA is trained with the LyCORIS module, and you're using the [a1111-sd-webui-locon](https://github.com/KohakuBlueleaf/a1111-sd-webui-locon) extension to load it.
- However, the [a1111-sd-webui-locon](https://github.com/KohakuBlueleaf/a1111-sd-webui-locon) extension is deprecated. I still use it for backward compatibility.
- Automatic1111 now supports LoRA with expanded Conv2d, also known as LoCon, and it has a code conflict with LoCon extensions since May 15th.

That's why the LoRA can't be loaded. This is also mentioned in the LoCon extension repository
- https://github.com/KohakuBlueleaf/a1111-sd-webui-locon/issues/40 <-- similar with your issue
- https://github.com/KohakuBlueleaf/a1111-sd-webui-locon/issues/38 <-- similar with @YellowStar11 

For a temporary fix, don't set `update extensions` to `True`. I pushed a commit last night to set it to `False` by default. Also, avoid using `AUTOMATIC1111-Dev` as it's a temporary fix. If you're looking for a long-term solution, here are some options:

1. If it's LoCon without `cp_decomposition`, try loading it in [sd-webui-additional-networks](https://github.com/kohya-ss/sd-webui-additional-networks).
2. I have also installed [a1111-sd-webui-lycoris](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris), which is a continuation of [a1111-sd-webui-locon](https://github.com/KohakuBlueleaf/a1111-sd-webui-locon). If the same error occurs again:
   - You can change the prefix for your LoRA from `<lora:...` to `<lyco:....`.
   - Or load your LoCon from the Lycoris tab in the extra network. I centralized all LoRA paths to the folder `/models/LoRA`, so you can load LoRA implementations from Kohya, Lycoris, or Automatic1111 from there.

I also plan to delete [a1111-sd-webui-locon](https://github.com/KohakuBlueleaf/a1111-sd-webui-locon) after all the problems are resolved. I know it's complicated, but because there are no universal rules to implement LoRA, people now make their own implementations, resulting in the same LoRA being different due to different algorithms.

Thank you.

**Comment by PhoenixEugene** [comment]
Thank you so much for the thorough explanation! I'll be trying today with "update extension" set to false as you suggested. Again, thanks!
