### ISSUE TITLE
    TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by LukeOvermind** [Linaqruf/sd-notebook-collection#48]
Hi, with every generation I am getting this error. Does not look like it has any negative effect on the performance or the generations. Just thought I will bring it to your attention. 

*** Error running before_process: /content/cagliostro-colab-ui/extensions-builtin/extra-options-section/scripts/extra_options_section.py
    Traceback (most recent call last):
      File "/content/cagliostro-colab-ui/modules/scripts.py", line 467, in before_process
        script.before_process(p, *script_args)
      File "/content/cagliostro-colab-ui/extensions-builtin/extra-options-section/scripts/extra_options_section.py", line 40, in before_process
        for name, value in zip(self.setting_names, args):
    TypeError: 'NoneType' object is not iterable

**Comment by LukeOvermind** [comment]
thanks my guy!
